export const airlines = [
  {
    airlineId: 1,
    airlineName: "Delta Airlines",
    country: "United States",
    logo: "/logos/delta.png",
    slogan: "Keep Climbing",
    headQuarters: "Atlanta, Georgia, USA",
    website: "https://www.delta.com",
    established: "1929",
    popularity: 9.5,
    fleetSize: 800,
    international: true,
    tags: ["legacy", "international", "domestic", "SkyTeam"],
    destination: "New York, USA"
  },
  {
    airlineId: 2,
    airlineName: "Emirates",
    country: "United Arab Emirates",
    logo: "/logos/emirates.png",
    slogan: "Fly Better",
    headQuarters: "Dubai, UAE",
    website: "https://www.emirates.com",
    established: "1985",
    popularity: 9.8,
    fleetSize: 260,
    international: true,
    tags: ["luxury", "long-haul", "international", "hub-Dubai"],
    destination: "London, UK"
  },
  {
    airlineId: 3,
    airlineName: "Qatar Airways",
    country: "Qatar",
    logo: "/logos/qatar.png",
    slogan: "Going Places Together",
    headQuarters: "Doha, Qatar",
    website: "https://www.qatarairways.com",
    established: "1993",
    popularity: 9.7,
    fleetSize: 250,
    international: true,
    tags: ["luxury", "international", "oneworld"],
    destination: "Doha, Qatar" 
  },
  {
    airlineId: 4,
    airlineName: "Singapore Airlines",
    country: "Singapore",
    logo: "/logos/singapore.png",
    slogan: "A Great Way to Fly",
    headQuarters: "Singapore",
    website: "https://www.singaporeair.com",
    established: "1947",
    popularity: 9.6,
    fleetSize: 140,
    international: true,
    tags: ["luxury", "international", "StarAlliance"],
    destination: "Singapore" 
  },
  {
    airlineId: 5,
    airlineName: "British Airways",
    country: "United Kingdom",
    logo: "/logos/british-airways.png",
    slogan: "To Fly. To Serve.",
    headQuarters: "London, England, UK",
    website: "https://www.britishairways.com",
    established: "1974",
    popularity: 9.2,
    fleetSize: 280,
    international: true,
    tags: ["legacy", "international", "oneworld"],
    destination: "Dubai, UAE"
  }
];
