export const airlines = [
  {
    airlineId: 1,
    aircraftId: 101,
    model: "Boeing 737",
    airlineName: "Delta Airlines",
    country: "United States",
    logo: "/logos/delta.png",
    slogan: "Keep Climbing",
    headQuarters: "Atlanta, Georgia, USA",
    website: "https://www.delta.com",
    established: "1929",
    popularity: 9.5,
    capacity: 800,
    international: true,
    tags: ["legacy", "international", "domestic", "SkyTeam"],
    destination: "New York, USA"
  },
  {
    airlineId: 1,
    aircraftId: 102,
    model: "Airbus A320",
    airlineName: "Delta Airlines",
    country: "United States",
    logo: "/logos/delta.png",
    slogan: "Keep Climbing",
    headQuarters: "Atlanta, Georgia, USA",
    website: "https://www.delta.com",
    established: "1929",
    popularity: 9.3,
    capacity: 800,
    international: true,
    tags: ["legacy", "international", "domestic", "SkyTeam"],
    destination: "Los Angeles, USA"
  },
  {
    airlineId: 1,
    aircraftId: 103,
    model: "Boeing 767",
    airlineName: "Delta Airlines",
    country: "United States",
    logo: "/logos/delta.png",
    slogan: "Keep Climbing",
    headQuarters: "Atlanta, Georgia, USA",
    website: "https://www.delta.com",
    established: "1929",
    popularity: 9.4,
    capacity: 800,
    international: true,
    tags: ["legacy", "international", "domestic", "SkyTeam"],
    destination: "Paris, France"
  },
  {
    airlineId: 2,
    aircraftId: 201,
    model: "Boeing 777",
    airlineName: "Emirates",
    country: "United Arab Emirates",
    logo: "/logos/emirates.png",
    slogan: "Fly Better",
    headQuarters: "Dubai, UAE",
    website: "https://www.emirates.com",
    established: "1985",
    popularity: 9.8,
    capacity: 260,
    international: true,
    tags: ["luxury", "long-haul", "international", "hub-Dubai"],
    destination: "London, UK"
  },
  {
    airlineId: 3,
    aircraftId: 301,
    model: "Airbus A350",
    airlineName: "Qatar Airways",
    country: "Qatar",
    logo: "/logos/qatar.png",
    slogan: "Going Places Together",
    headQuarters: "Doha, Qatar",
    website: "https://www.qatarairways.com",
    established: "1993",
    popularity: 9.7,
    capacity: 250,
    international: true,
    tags: ["luxury", "international", "oneworld"],
    destination: "Doha, Qatar"
  },
  {
    airlineId: 4,
    aircraftId: 401,
    model: "Boeing 787 Dreamliner",
    airlineName: "Singapore Airlines",
    country: "Singapore",
    logo: "/logos/singapore.png",
    slogan: "A Great Way to Fly",
    headQuarters: "Singapore",
    website: "https://www.singaporeair.com",
    established: "1947",
    popularity: 9.6,
    capacity: 140,
    international: true,
    tags: ["luxury", "international", "StarAlliance"],
    destination: "Singapore"
  },
  {
    airlineId: 5,
    aircraftId: 501,
    model: "Airbus A380",
    airlineName: "British Airways",
    country: "United Kingdom",
    logo: "/logos/british-airways.png",
    slogan: "To Fly. To Serve.",
    headQuarters: "London, England, UK",
    website: "https://www.britishairways.com",
    established: "1974",
    popularity: 9.2,
    capacity: 280,
    international: true,
    tags: ["legacy", "international", "oneworld"],
    destination: "Dubai, UAE"
  }
];


  
